# Generated by Django 2.2 on 2020-09-20 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gricapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_consumer',
        ),
        migrations.AddField(
            model_name='user',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
    ]
