# Generated by Django 2.2 on 2020-09-26 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gricapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produce',
            name='produce_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='gricapi.Category'),
        ),
        migrations.AlterField(
            model_name='produce',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
