# Generated by Django 2.2 on 2020-09-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gricapi', '0002_auto_20200920_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_farmer',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_investor',
        ),
        migrations.AddField(
            model_name='produce',
            name='price_tag',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_farmer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_investor',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produce',
            name='measurement_unit',
            field=models.CharField(choices=[('Bags', 'bags'), ('Tonnes', 'tonnes'), ('Single units(Retail)', 'units')], default='bags', max_length=25),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
