# Generated by Django 2.2 on 2020-10-02 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gricapi', '0004_auto_20201001_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200),
        ),
    ]
